# 01. Array Foundations & Memory Mechanics: Beginner Guide

### 🌟 What Are NumPy Array Foundations & Memory Mechanics?
**NumPy (Numerical Python)** is the core library for numerical computing in Python. Standard Python lists store scattered object references, which makes math slow. NumPy introduces the **`ndarray` (N-Dimensional Array)**—a flat, contiguous block of memory where all elements share the same data type. This notebook teaches how memory is allocated, how to initialize arrays, and how to inspect array properties.

This interactive guide loads and works directly with `data/raw_transactions.csv`, giving you real-world hands-on practice.

### 📚 Key Concepts Covered in this Notebook:
- **Homogeneous Memory Allocation**: Flat contiguous C-memory buffer storing raw binary bytes without PyObject wrapper overhead.
- **Array Creation Routines**: Covers `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, and `np.full()`.
- **Sequence Generation**: Covers `np.arange()`, `np.linspace()`, and `np.logspace()`.
- **Inspecting Properties**: Covers `.ndim`, `.shape`, `.size`, `.dtype`, `.itemsize`, and `.nbytes`.


In [1]:
# Setup imports & dataset loading from raw_transactions.csv
import numpy as np
import pandas as pd
import sys
import time
import os

# Load raw transactions and extract aligned NumPy numeric arrays
csv_path = 'data/raw_transactions.csv' if os.path.exists('data/raw_transactions.csv') else '../data/raw_transactions.csv'
raw_df = pd.read_csv(csv_path)
clean_raw = raw_df.dropna(subset=['transaction_amount', 'is_fraud', 'account_age_months']).reset_index(drop=True)
amounts = clean_raw['transaction_amount'].to_numpy(dtype=np.float64)
fraud_flags = clean_raw['is_fraud'].to_numpy(dtype=np.int8)
account_ages = clean_raw['account_age_months'].to_numpy(dtype=np.float32)

print(f"NumPy Version: {np.__version__}")
print(f"Loaded from {csv_path} ({len(amounts)} clean aligned rows):")
print(f"- amounts array: shape {amounts.shape}, dtype {amounts.dtype}")
print(f"- fraud_flags array: shape {fraud_flags.shape}, dtype {fraud_flags.dtype}")
print(f"- account_ages array: shape {account_ages.shape}, dtype {account_ages.dtype}")

NumPy Version: 1.26.4
Loaded from ../data/raw_transactions.csv (14262 clean aligned rows):
- amounts array: shape (14262,), dtype float64
- fraud_flags array: shape (14262,), dtype int8
- account_ages array: shape (14262,), dtype float32


### 🔹 Constructing Arrays: `np.array()`
Creates an `ndarray` from transaction amount lists. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `np.array(amounts[:10], dtype=np.float64)`


In [2]:
amt_sample = np.array(amounts[:5], dtype=np.float64)
print('Constructed Amount Array:', amt_sample)
print('Dtype:', amt_sample.dtype)

Constructed Amount Array: [1216.33  324.99  136.66  124.21 1284.68]
Dtype: float64


### 🔹 Allocating Zeros: `np.zeros()`
Allocates zeroed memory of shape matching transaction subsets. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Always specify your desired `dtype` (like `np.float32` or `np.int32`) to prevent allocating unnecessary 64-bit precision when 32-bit suffices.

**Syntax:** `np.zeros(len(amounts), dtype=np.float32)`


In [3]:
zeros_weights = np.zeros((4, 4), dtype=np.float64)
print('Zeros Weight Matrix (4, 4):\n', zeros_weights)

Zeros Weight Matrix (4, 4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 🔹 Allocating Ones: `np.ones()`
Allocates ones initialized array for scaling factors. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Always specify your desired `dtype` (like `np.float32` or `np.int32`) to prevent allocating unnecessary 64-bit precision when 32-bit suffices.

**Syntax:** `np.ones(shape=(3, 3), dtype=np.int32)`


In [4]:
ones_scale = np.ones((2, 3), dtype=np.int32)
print('Ones Array:\n', ones_scale)

Ones Array:
 [[1 1 1]
 [1 1 1]]


### 🔹 Uninitialized Fast Memory: `np.empty()`
Fastest allocation routine returning raw uninitialized RAM bytes. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Always specify your desired `dtype` (like `np.float32` or `np.int32`) to prevent allocating unnecessary 64-bit precision when 32-bit suffices.

**Syntax:** `np.empty(shape=(2, 2))`


In [5]:
empty_buf = np.empty((2, 2), dtype=np.float64)
print('Empty Uninitialized Memory:\n', empty_buf)

Empty Uninitialized Memory:
 [[0.00000000e+000 1.34543641e-311]
 [1.34543641e-311 1.34543641e-311]]


### 🔹 Constant-Filled Array: `np.full()`
Fills an array of transaction count with default risk score 0.5. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Always specify your desired `dtype` (like `np.float32` or `np.int32`) to prevent allocating unnecessary 64-bit precision when 32-bit suffices.

**Syntax:** `np.full(shape=(5,), fill_value=0.5)`


In [6]:
default_risk = np.full(shape=(5,), fill_value=0.5)
print('Default Risk Scores:', default_risk)

Default Risk Scores: [0.5 0.5 0.5 0.5 0.5]


### 🔹 Stepped Range Sequence: `np.arange()`
Generates integer transaction index offsets. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Use `np.arange(start, stop, step)` when you know the step size. Use `np.linspace(start, stop, num)` when you know the exact number of points you want.

**Syntax:** `np.arange(0, 10, 2)`


In [7]:
idx_offsets = np.arange(0, 10, 2)
print('Stepped Range:', idx_offsets)

Stepped Range: [0 2 4 6 8]


### 🔹 Linear Evenly Spaced Grids: `np.linspace()`
Generates evenly spaced threshold intervals between min and max transaction amount. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** Use `np.arange(start, stop, step)` when you know the step size. Use `np.linspace(start, stop, num)` when you know the exact number of points you want.

**Syntax:** `np.linspace(amounts.min(), amounts.max(), num=5)`


In [8]:
spend_grid = np.linspace(amounts.min(), amounts.max(), num=5)
print('Linspace Grid from Min to Max Transaction Amount:', spend_grid.round(2))

Linspace Grid from Min to Max Transaction Amount: [   5.08  503.8  1002.53 1501.26 1999.98]


### 🔹 Logarithmic Grids: `np.logspace()`
Generates geometrically spaced transaction cutoff points. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `np.logspace(1, 4, num=4)`


In [9]:
log_cutoffs = np.logspace(1, 4, num=4)
print('Logarithmic Cutoffs ($10 to $10,000):', log_cutoffs)

Logarithmic Cutoffs ($10 to $10,000): [   10.   100.  1000. 10000.]


### 🔹 Inspecting Dimensions: `.ndim`
Returns array dimension rank. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `amounts.ndim`


In [10]:
print('Amounts Array Dimensions (ndim):', amounts.ndim)

Amounts Array Dimensions (ndim): 1


### 🔹 Inspecting Shape: `.shape`
Returns total transaction count tuple. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `amounts.shape`


In [11]:
print('Amounts Array Shape:', amounts.shape)

Amounts Array Shape: (14262,)


### 🔹 Inspecting Total Elements: `.size`
Returns total transaction elements count. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `amounts.size`


In [12]:
print('Total Elements in Amounts:', amounts.size)

Total Elements in Amounts: 14262


### 🔹 Inspecting Dtype: `.dtype`
Returns binary primitive data type. Checking and validating data types prevents subtle runtime errors and ensures subsequent mathematical or string operations behave properly. **Tip:** Prefer `isinstance(obj, ClassName)` over `type(obj) == ClassName` when checking types in conditional logic.

**Syntax:** `amounts.dtype`


In [13]:
print('Amounts Data Type:', amounts.dtype)

Amounts Data Type: float64


### 🔹 Inspecting Item Size: `.itemsize`
Returns bytes per transaction element (8 bytes for float64). NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `amounts.itemsize`


In [14]:
print('Bytes per Element (itemsize):', amounts.itemsize)

Bytes per Element (itemsize): 8


### 🔹 Inspecting Buffer Memory: `.nbytes`
Calculates total raw RAM consumed by the transaction amounts vector. NumPy runs in compiled C memory buffers, enabling mathematical operations across millions of numbers simultaneously in milliseconds. **Tip:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

**Syntax:** `amounts.nbytes`


In [15]:
print(f'Total Memory Footprint (nbytes): {amounts.nbytes} bytes ({amounts.nbytes / 1024:.2f} KB)')

Total Memory Footprint (nbytes): 114096 bytes (111.42 KB)


## 💡 Real-World Practice & Scenarios
Practical scenarios and common data questions explained simply with real examples.


### 🔍 Scenario: Q1: Memory Consumption: Python Float List vs NumPy Transaction Vector

**Approach:** Compare memory footprint of transaction amounts in Python float list vs NumPy float64 ndarray.
**Syntax:** `sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)` vs `amounts.nbytes`


In [16]:
py_amounts = list(amounts)
py_mem = sys.getsizeof(py_amounts) + sum(sys.getsizeof(x) for x in py_amounts)
np_mem = amounts.nbytes
print(f'Python List Memory ({len(amounts)} floats): {py_mem / 1024:.1f} KB')
print(f'NumPy ndarray Memory ({len(amounts)} floats): {np_mem / 1024:.1f} KB ({(1 - np_mem/py_mem)*100:.1f}% RAM reduction)')

Python List Memory (14262 floats): 557.2 KB
NumPy ndarray Memory (14262 floats): 111.4 KB (80.0% RAM reduction)
