# 01. Array Foundations & Memory Mechanics: Beginner Guide

### 📌 Overview & Architectural Context
Welcome to **01. Array Foundations & Memory Mechanics**. At the core of numerical computing in Python is NumPy's N-dimensional array (`ndarray`), a homogeneous, contiguous block of memory managed via metadata descriptors (shape, strides, dtype, and flags). This notebook explores array creation factory functions (`array`, `zeros`, `ones`, `empty`, `full`, `arange`, `linspace`, `logspace`, `geomspace`, `eye`, `diag`), structural dimension introspection (`ndim`, `shape`, `size`, `itemsize`, `nbytes`), and explicit deep copy mechanics (`copy`).

### 📚 Key Concepts Covered in this Notebook:
- [x] 🔹 Array Construction: `np.array()`
- [x] 🔹 Zero-Filled Array: `np.zeros()`
- [x] 🔹 Ones-Filled Array: `np.ones()`
- [x] 🔹 Uninitialized Memory Allocation: `np.empty()`
- [x] 🔹 Constant Value Array: `np.full()`
- [x] 🔹 Stepped Range Sequence: `np.arange()`
- [x] 🔹 Linear Evenly Spaced Grids: `np.linspace()`
- [x] 🔹 Logarithmic Grids: `np.logspace()`
- [x] 🔹 Inspecting Dimensions: `.ndim`
- [x] 🔹 Inspecting Shape: `.shape`
- [x] 🔹 Inspecting Total Elements: `.size`
- [x] 🔹 Inspecting Dtype: `.dtype`
- [x] 🔹 Inspecting Item Size: `.itemsize`
- [x] 🔹 Inspecting Buffer Memory: `.nbytes`


In [1]:
# Setup imports & dataset loading from raw_transactions.csv
import numpy as np
import pandas as pd
import sys
import time
import os

# Load raw transactions and extract aligned NumPy numeric arrays
csv_path = 'data/raw_transactions.csv' if os.path.exists('data/raw_transactions.csv') else '../data/raw_transactions.csv'
raw_df = pd.read_csv(csv_path)
clean_raw = raw_df.dropna(subset=['transaction_amount', 'is_fraud', 'account_age_months']).reset_index(drop=True)
amounts = clean_raw['transaction_amount'].to_numpy(dtype=np.float64)
fraud_flags = clean_raw['is_fraud'].to_numpy(dtype=np.int8)
account_ages = clean_raw['account_age_months'].to_numpy(dtype=np.float32)

print(f"NumPy Version: {np.__version__}")
print(f"Loaded from {csv_path} ({len(amounts)} clean aligned rows):")
print(f"- amounts array: shape {amounts.shape}, dtype {amounts.dtype}")
print(f"- fraud_flags array: shape {fraud_flags.shape}, dtype {fraud_flags.dtype}")
print(f"- account_ages array: shape {account_ages.shape}, dtype {account_ages.dtype}")

NumPy Version: 1.26.4
Loaded from ../data/raw_transactions.csv (14251 clean aligned rows):
- amounts array: shape (14251,), dtype float64
- fraud_flags array: shape (14251,), dtype int8
- account_ages array: shape (14251,), dtype float32


### 🔹 Array Construction: `np.array()`
- **What it does:** Constructs an N-dimensional array (ndarray) from an array-like sequence with specified data type and memory order.
- **Syntax:** `np.array()`
  - **Parameters:**
    - `object` (*array_like*): An array, sequence, or nested iterable.
  - **Optional Parameters:**
    - `dtype` (*data-type, optional*): Desired data-type for array.
    - `copy` (*bool, default True*): Whether to copy input data.
- **Key Note:** NumPy arrays enforce homogeneous data types, enabling SIMD vectorization and high CPU cache performance.
- **Dataset Application & Code Demonstration:** Applies Array Construction across the extracted numeric transaction `amounts` array to compute performance metrics.


In [2]:
amt_sample = np.array(amounts[:5], dtype=np.float64)
print('Constructed Amount Array:', amt_sample)
print('Dtype:', amt_sample.dtype)

Constructed Amount Array: [ 607.78 1819.11   64.08 1025.73  772.74]
Dtype: float64


### 🔹 Zero-Filled Array: `np.zeros()`
- **What it does:** Returns a new array of given shape and type, initialized with zeros.
- **Syntax:** `np.zeros()`
  - **Parameters:**
    - `shape` (*int or tuple of ints*): Shape of the new array.
  - **Optional Parameters:**
    - `dtype` (*data-type, default float*): Desired output data-type.
- **Key Note:** `np.zeros` zeroes out memory pages, ensuring reproducible zero initialization.
- **Dataset Application & Code Demonstration:** Demonstrates Zero-Filled Array with practical fintech data structures and variables in the following code block.


In [3]:
zeros_weights = np.zeros((4, 4), dtype=np.float64)
print('Zeros Weight Matrix (4, 4):\n', zeros_weights)

Zeros Weight Matrix (4, 4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 🔹 Ones-Filled Array: `np.ones()`
- **What it does:** Returns a new array of given shape and type, filled with ones.
- **Syntax:** `np.ones()`
  - **Parameters:**
    - `shape` (*int or tuple of ints*): Shape of the new array.
  - **Optional Parameters:**
    - `dtype` (*data-type, default float*): Desired output data-type.
- **Key Note:** Useful for initializing identity weights, unit scaling vectors, and multiplication identities.
- **Dataset Application & Code Demonstration:** Demonstrates Ones-Filled Array with practical fintech data structures and variables in the following code block.


In [4]:
ones_scale = np.ones((2, 3), dtype=np.int32)
print('Ones Array:\n', ones_scale)

Ones Array:
 [[1 1 1]
 [1 1 1]]


### 🔹 Uninitialized Memory Allocation: `np.empty()`
- **What it does:** Returns a new array of given shape and type without initializing memory buffer entries (contains uninitialized values).
- **Syntax:** `np.empty()`
  - **Parameters:**
    - `row_indexer` (*scalar, slice, list, or boolean mask*): Row identifier(s).
  - **Optional Parameters:**
    - `col_indexer` (*scalar, slice, list, or boolean mask*): Column identifier(s).
- **Key Note:** `np.empty()` is the fastest array allocation method because it skips zero-filling RAM; always overwrite before reading.
- **Dataset Application & Code Demonstration:** Demonstrates Uninitialized Memory Allocation with practical fintech data structures and variables in the following code block.


In [5]:
empty_buf = np.empty((2, 2), dtype=np.float64)
print('Empty Uninitialized Memory:\n', empty_buf)

Empty Uninitialized Memory:
 [[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 3.11522054e-307]]


### 🔹 Constant Value Array: `np.full()`
- **What it does:** Returns a new array of given shape and type, filled with a specified scalar constant value.
- **Syntax:** `np.full()`
  - **Parameters:**
    - `shape` (*int or tuple of ints*): Shape of the array.
    - `fill_value` (*scalar or array_like*): Fill value.
  - **Optional Parameters:**
    - `dtype` (*data-type, optional*): Output data-type.
- **Key Note:** Equivalent to `np.empty(shape) * fill_value` but faster and type-safe.
- **Dataset Application & Code Demonstration:** Demonstrates Constant Value Array with practical fintech data structures and variables in the following code block.


In [6]:
default_risk = np.full(shape=(5,), fill_value=0.5)
print('Default Risk Scores:', default_risk)

Default Risk Scores: [0.5 0.5 0.5 0.5 0.5]


### 🔹 Stepped Range Sequence: `np.arange()`
- **What it does:** Generates integer elements index offsets.
- **Syntax:** `np.arange()`
  - **Parameters:**
    - `stop` (*number*): End of interval (exclusive).
  - **Optional Parameters:**
    - `start` (*number, default 0*): Start of interval.
    - `step` (*number, default 1*): Spacing between values.
- **Key Note:** Use `np.arange(start, stop, step)` when you know the step size. Use `np.linspace(start, stop, num)` when you know the exact number of points you want.
- **Dataset Application & Code Demonstration:** Demonstrates Stepped Range Sequence with practical fintech data structures and variables in the following code block.


In [7]:
idx_offsets = np.arange(0, 10, 2)
print('Stepped Range:', idx_offsets)

Stepped Range: [0 2 4 6 8]


### 🔹 Linear Evenly Spaced Grids: `np.linspace()`
- **What it does:** Generates evenly spaced threshold intervals between min and max numerical values.
- **Syntax:** `np.linspace()`
  - **Parameters:**
    - `start` (*scalar*): Starting value.
    - `stop` (*scalar*): Ending value.
  - **Optional Parameters:**
    - `num` (*int, default 50*): Number of samples to generate.
    - `endpoint` (*bool, default True*): Include stop point.
- **Key Note:** Use `np.arange(start, stop, step)` when you know the step size. Use `np.linspace(start, stop, num)` when you know the exact number of points you want.
- **Dataset Application & Code Demonstration:** Applies Linear Evenly Spaced Grids across the extracted numeric transaction `amounts` array to compute performance metrics.


In [8]:
spend_grid = np.linspace(amounts.min(), amounts.max(), num=5)
print('Linspace Grid from Min to Max Transaction Amount:', spend_grid.round(2))

Linspace Grid from Min to Max Transaction Amount: [   5.02  503.76 1002.5  1501.24 1999.98]


### 🔹 Logarithmic Grids: `np.logspace()`
- **What it does:** Generates geometrically spaced elements cutoff points.
- **Syntax:** `np.logspace()`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.
- **Dataset Application & Code Demonstration:** Demonstrates Logarithmic Grids with practical fintech data structures and variables in the following code block.


In [9]:
log_cutoffs = np.logspace(1, 4, num=4)
print('Logarithmic Cutoffs ($10 to $10,000):', log_cutoffs)

Logarithmic Cutoffs ($10 to $10,000): [   10.   100.  1000. 10000.]


### 🔹 Inspecting Dimensions: `.ndim`
- **What it does:** Returns an integer representing the number of array dimensions (axes).
- **Syntax:** `ndarray.ndim`
- **Key Note:** 1D array has `.ndim == 1`, 2D matrix has `.ndim == 2`, 3D tensor has `.ndim == 3`.
- **Dataset Application & Code Demonstration:** Applies Inspecting Dimensions across the extracted numeric transaction `amounts` array to compute performance metrics.


In [10]:
print('Amounts Array Dimensions (ndim):', amounts.ndim)

Amounts Array Dimensions (ndim): 1


### 🔹 Inspecting Shape: `.shape`
- **What it does:** Returns a tuple of integers indicating the size of the array along each dimension.
- **Syntax:** `ndarray.shape / DataFrame.shape / Series.shape`
- **Key Note:** `.shape` is a property; modifying `ndarray.shape` directly reshapes in-place without memory copying if contiguous.
- **Dataset Application & Code Demonstration:** Applies Inspecting Shape across the extracted numeric transaction `amounts` array to compute performance metrics.


In [11]:
print('Amounts Array Shape:', amounts.shape)

Amounts Array Shape: (14251,)


### 🔹 Inspecting Total Elements: `.size`
- **What it does:** Returns the total number of elements contained across all dimensions.
- **Syntax:** `ndarray.size / Series.size`
- **Key Note:** For 2D array of shape (4, 4), `.size == 16`.
- **Dataset Application & Code Demonstration:** Applies Inspecting Total Elements across the extracted numeric transaction `amounts` array to compute performance metrics.


In [12]:
print('Total Elements in Amounts:', amounts.size)

Total Elements in Amounts: 14251


### 🔹 Inspecting Dtype: `.dtype`
- **What it does:** Returns the data type object (dtype) describing the element type and byte order.
- **Syntax:** `ndarray.dtype / Series.dtype`
- **Key Note:** Homogeneous data types ensure maximum SIMD CPU cache alignment.
- **Dataset Application & Code Demonstration:** Applies Inspecting Dtype across the extracted numeric transaction `amounts` array to compute performance metrics.


In [13]:
print('Amounts Data Type:', amounts.dtype)

Amounts Data Type: float64


### 🔹 Inspecting Item Size: `.itemsize`
- **What it does:** Returns the total number of elements contained across all dimensions.
- **Syntax:** `ndarray.size / Series.size`
- **Key Note:** For 2D array of shape (4, 4), `.size == 16`.
- **Dataset Application & Code Demonstration:** Applies Inspecting Item Size across the extracted numeric transaction `amounts` array to compute performance metrics.


In [14]:
print('Bytes per Element (itemsize):', amounts.itemsize)

Bytes per Element (itemsize): 8


### 🔹 Inspecting Buffer Memory: `.nbytes`
- **What it does:** Returns the total number of bytes consumed by the elements of the array in RAM.
- **Syntax:** `ndarray.nbytes`
- **Key Note:** Does not include memory consumed by array container object overhead.
- **Dataset Application & Code Demonstration:** Applies Inspecting Buffer Memory across the extracted numeric transaction `amounts` array to compute performance metrics.


In [15]:
print(f'Total Memory Footprint (nbytes): {amounts.nbytes} bytes ({amounts.nbytes / 1024:.2f} KB)')

Total Memory Footprint (nbytes): 114008 bytes (111.34 KB)


## 💡 Real-World Practice & Scenarios
Practical scenarios and common data engineering questions explained with real examples.


### 🔍 Scenario: Q1: Memory Consumption: Python Float List vs NumPy Transaction Vector
- **Objective:** Q1: Memory Consumption: Python Float List vs NumPy Transaction Vector
- **Approach:** Compare memory footprint of transaction amounts in Python float list vs NumPy float64 ndarray.
- **Syntax:** `sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)` vs `amounts.nbytes`

In [16]:
py_amounts = list(amounts)
py_mem = sys.getsizeof(py_amounts) + sum(sys.getsizeof(x) for x in py_amounts)
np_mem = amounts.nbytes
print(f'Python List Memory ({len(amounts)} floats): {py_mem / 1024:.1f} KB')
print(f'NumPy ndarray Memory ({len(amounts)} floats): {np_mem / 1024:.1f} KB ({(1 - np_mem/py_mem)*100:.1f}% RAM reduction)')

Python List Memory (14251 floats): 556.7 KB
NumPy ndarray Memory (14251 floats): 111.3 KB (80.0% RAM reduction)
