# 11. Linear Algebra & Matrix Decompositions (5+ Years Interview Guide)
Exhaustive revision guide to matrix products (@, matmul, dot), linear system solvers (solve), matrix inversion (inv), and factorizations (eig, svd, qr) on transaction covariance matrices.

### Key 5-Year Interview Concepts Covered:
- **Matrix Multiplication**: Dedicated cell for `@` operator, `np.matmul()`, and `np.dot()`.
- **Linear Solvers**: Dedicated cell for `np.linalg.solve()` and `np.linalg.inv()`.
- **Matrix Factorizations**: Dedicated cell for `np.linalg.eig()`, `np.linalg.svd()`, and `np.linalg.qr()`.

This interactive revision guide loads and operates directly on `data/raw_transactions.csv` using dedicated cells per method.

In [1]:
# Setup imports & dataset loading from raw_transactions.csv
import numpy as np
import pandas as pd
import sys
import time
import os

# Load raw transactions and extract aligned NumPy numeric arrays
csv_path = 'data/raw_transactions.csv' if os.path.exists('data/raw_transactions.csv') else '../data/raw_transactions.csv'
raw_df = pd.read_csv(csv_path)
clean_raw = raw_df.dropna(subset=['transaction_amount', 'is_fraud', 'account_age_months']).reset_index(drop=True)
amounts = clean_raw['transaction_amount'].to_numpy(dtype=np.float64)
fraud_flags = clean_raw['is_fraud'].to_numpy(dtype=np.int8)
account_ages = clean_raw['account_age_months'].to_numpy(dtype=np.float32)

print(f"NumPy Version: {np.__version__}")
print(f"Loaded from {csv_path} ({len(amounts)} clean aligned rows):")
print(f"- amounts array: shape {amounts.shape}, dtype {amounts.dtype}")
print(f"- fraud_flags array: shape {fraud_flags.shape}, dtype {fraud_flags.dtype}")
print(f"- account_ages array: shape {account_ages.shape}, dtype {account_ages.dtype}")

NumPy Version: 1.26.4
Loaded from data/raw_transactions.csv (14262 clean aligned rows):
- amounts array: shape (14262,), dtype float64
- fraud_flags array: shape (14262,), dtype int8
- account_ages array: shape (14262,), dtype float32


### Matrix Multiplication with the `@` Operator
**Explanation**: Multiplies transaction feature matrix by weight vector.

**Syntax**: `X @ weights`

In [2]:
X = np.column_stack([amounts[:100]/100, account_ages[:100]/10])
w = np.array([0.6, 0.4])
risk_scores = X @ w
print('Linear Composite Risk Scores Head:', risk_scores[:5].round(3))

Linear Composite Risk Scores Head: [ 9.538  6.43   3.54   2.745 11.548]


### Dot Products with `np.dot()`
**Explanation**: Computes vector dot products for portfolio valuation.

**Syntax**: `np.dot(amounts[:5], np.ones(5))`

In [3]:
print('Total Spend via Dot Product:', np.dot(amounts[:5], np.ones(5)).round(2))

Total Spend via Dot Product: 3086.87


### Solving Linear Systems with `np.linalg.solve()`
**Explanation**: Solves ordinary least squares system equations $X^T X \beta = X^T y$.

**Syntax**: `np.linalg.solve(A, b)`

In [4]:
A = (X.T @ X)
b = (X.T @ amounts[:100])
beta = np.linalg.solve(A, b)
print('Fitted OLS Beta Coefficients:', beta.round(4))

Fitted OLS Beta Coefficients: [100.  -0.]


### Matrix Inversion with `np.linalg.inv()`
**Explanation**: Inverts covariance matrix $(X^T X)^{-1}$.

**Syntax**: `np.linalg.inv(cov_matrix)`

In [5]:
A_inv = np.linalg.inv(A)
print('Inverse Covariance Matrix (A^-1):\n', A_inv)

Inverse Covariance Matrix (A^-1):
 [[ 0.00017225 -0.00020359]
 [-0.00020359  0.00042212]]


### Eigenvalue Decomposition with `np.linalg.eig()`
**Explanation**: Computes eigenvalues and principal directions from transaction covariance matrix.

**Syntax**: `w, v = np.linalg.eig(cov_mat)`

In [6]:
cov_mat = np.cov(X.T)
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
print('Covariance Eigenvalues:', eig_vals.round(4))
print('Eigenvectors:\n', eig_vecs.round(4))

Covariance Eigenvalues: [33.9328 14.2109]
Eigenvectors:
 [[ 0.9995 -0.0318]
 [ 0.0318  0.9995]]


### Singular Value Decomposition with `np.linalg.svd()`
**Explanation**: Factorizes transaction feature matrix into $U \Sigma V^T$ for PCA dimensionality reduction.

**Syntax**: `U, S, Vt = np.linalg.svd(X, full_matrices=False)`

In [7]:
U, S, Vt = np.linalg.svd(X, full_matrices=False)
print('Singular Values (S):', S.round(4))
print('Principal Component Weights (Vt):\n', Vt.round(4))

Singular Values (S): [130.9475  43.191 ]
Principal Component Weights (Vt):
 [[-0.8726 -0.4884]
 [ 0.4884 -0.8726]]


### QR Decomposition with `np.linalg.qr()`
**Explanation**: Factorizes $X = QR$ where $Q$ is orthonormal and $R$ is upper triangular.

**Syntax**: `Q, R = np.linalg.qr(X)`

In [8]:
Q, R = np.linalg.qr(X)
print('Orthogonal Q Shape:', Q.shape, 'Upper Triangular R Shape:', R.shape)

Orthogonal Q Shape: (100, 2) Upper Triangular R Shape: (2, 2)


## Section: Senior Fintech Interview Scenarios (5+ Years Experience)

### Q1: Portfolio Risk Variance Calculation
**Explanation**: Given transaction asset weights $w$, calculate total portfolio variance $w^T \Sigma w$.

**Syntax**: `w.T @ cov_mat @ w`

In [9]:
port_var = w.T @ cov_mat @ w
print('Total Portfolio Variance:', round(port_var, 6))

Total Portfolio Variance: 14.786587
