# 11. Linear Algebra & Matrix Decompositions: Beginner Guide

### 📌 Overview
Master **11. Linear Algebra & Matrix Decompositions: Beginner Guide** with concise, zero-fluff bullet points and executable code on real Fintech records ([raw_transactions.csv](file:///data/raw_transactions.csv)).

### 📚 Key Concepts Covered in this Notebook:
- **Matrix Multiplication**: Covers `@` operator, `np.matmul()`, and `np.dot()`.
- **Linear Solvers**: Covers `np.linalg.solve()` and `np.linalg.inv()`.
- **Matrix Factorizations**: Covers `np.linalg.eig()`, `np.linalg.svd()`, and `np.linalg.qr()`.


In [1]:
# Setup imports & dataset loading from raw_transactions.csv
import numpy as np
import pandas as pd
import sys
import time
import os

# Load raw transactions and extract aligned NumPy numeric arrays
csv_path = 'data/raw_transactions.csv' if os.path.exists('data/raw_transactions.csv') else '../data/raw_transactions.csv'
raw_df = pd.read_csv(csv_path)
clean_raw = raw_df.dropna(subset=['transaction_amount', 'is_fraud', 'account_age_months']).reset_index(drop=True)
amounts = clean_raw['transaction_amount'].to_numpy(dtype=np.float64)
fraud_flags = clean_raw['is_fraud'].to_numpy(dtype=np.int8)
account_ages = clean_raw['account_age_months'].to_numpy(dtype=np.float32)

print(f"NumPy Version: {np.__version__}")
print(f"Loaded from {csv_path} ({len(amounts)} clean aligned rows):")
print(f"- amounts array: shape {amounts.shape}, dtype {amounts.dtype}")
print(f"- fraud_flags array: shape {fraud_flags.shape}, dtype {fraud_flags.dtype}")
print(f"- account_ages array: shape {account_ages.shape}, dtype {account_ages.dtype}")

NumPy Version: 1.26.4
Loaded from ../data/raw_transactions.csv (14251 clean aligned rows):
- amounts array: shape (14251,), dtype float64
- fraud_flags array: shape (14251,), dtype int8
- account_ages array: shape (14251,), dtype float32


### 🔹 Matrix Multiplication with the `@` Operator
- **What it does:** Multiplies transaction feature matrix by weight vector.
- **Syntax:** `X @ weights`
- **Operation:** `X = np.column_stack([amounts[:100]/100, account_ages[:100]/10])`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [2]:
X = np.column_stack([amounts[:100]/100, account_ages[:100]/10])
w = np.array([0.6, 0.4])
risk_scores = X @ w
print('Linear Composite Risk Scores Head:', risk_scores[:5].round(3))

Linear Composite Risk Scores Head: [ 3.967 12.035  4.024  8.154  4.836]


### 🔹 Dot Products with `np.dot()`
- **What it does:** Computes vector dot products for portfolio valuation.
- **Syntax:** `np.dot(amounts[:5], np.ones(5))`
- **Operation:** `print('Total Spend via Dot Product:', np.dot(amounts[:5], np.ones(5)).round(2))`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [3]:
print('Total Spend via Dot Product:', np.dot(amounts[:5], np.ones(5)).round(2))

Total Spend via Dot Product: 4289.44


### 🔹 Solving Linear Systems with `np.linalg.solve()`
- **What it does:** Solves ordinary least squares system equations $X^T X \beta = X^T y$.
- **Syntax:** `np.linalg.solve(A, b)`
- **Operation:** `A = (X.T @ X)`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [4]:
A = (X.T @ X)
b = (X.T @ amounts[:100])
beta = np.linalg.solve(A, b)
print('Fitted OLS Beta Coefficients:', beta.round(4))

Fitted OLS Beta Coefficients: [100.   0.]


### 🔹 Matrix Inversion with `np.linalg.inv()`
- **What it does:** Inverts covariance matrix $(X^T X)^{-1}$.
- **Syntax:** `np.linalg.inv(cov_matrix)`
- **Operation:** `A_inv = np.linalg.inv(A)`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [5]:
A_inv = np.linalg.inv(A)
print('Inverse Covariance Matrix (A^-1):\n', A_inv)

Inverse Covariance Matrix (A^-1):
 [[ 0.00015598 -0.00017173]
 [-0.00017173  0.00039743]]


### 🔹 Eigenvalue Decomposition with `np.linalg.eig()`
- **What it does:** Computes eigenvalues and principal directions from transaction covariance matrix.
- **Syntax:** `w, v = np.linalg.eig(cov_mat)`
- **Operation:** `cov_mat = np.cov(X.T)`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [6]:
cov_mat = np.cov(X.T)
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
print('Covariance Eigenvalues:', eig_vals.round(4))
print('Eigenvectors:\n', eig_vecs.round(4))

Covariance Eigenvalues: [40.2633 13.4567]
Eigenvectors:
 [[ 0.9997  0.0231]
 [-0.0231  0.9997]]


### 🔹 Singular Value Decomposition with `np.linalg.svd()`
- **What it does:** Factorizes transaction feature matrix into $U \Sigma V^T$ for PCA dimensionality reduction.
- **Syntax:** `U, S, Vt = np.linalg.svd(X, full_matrices=False)`
- **Operation:** `U, S, Vt = np.linalg.svd(X, full_matrices=False)`
- **Key Note:** NumPy operations are optimized for homogeneous numeric data, offering massive speed improvements over standard Python loops.

In [7]:
U, S, Vt = np.linalg.svd(X, full_matrices=False)
print('Singular Values (S):', S.round(4))
print('Principal Component Weights (Vt):\n', Vt.round(4))

Singular Values (S): [122.3635  45.332 ]
Principal Component Weights (Vt):
 [[-0.8874 -0.4609]
 [-0.4609  0.8874]]


### 🔍 Scenario: QR Decomposition with `np.linalg.qr()`
- **Objective:** QR Decomposition with `np.linalg.qr()`
- **Approach:** Factorizes $X = QR$ where $Q$ is orthonormal and $R$ is upper triangular.
- **Syntax:** `Q, R = np.linalg.qr(X)`

In [8]:
Q, R = np.linalg.qr(X)
print('Orthogonal Q Shape:', Q.shape, 'Upper Triangular R Shape:', R.shape)

Orthogonal Q Shape: (100, 2) Upper Triangular R Shape: (2, 2)


## 💡 Real-World Practice & Scenarios
Practical scenarios and common data engineering questions explained with real examples.


### 🔍 Scenario: Q1: Portfolio Risk Variance Calculation
- **Objective:** Q1: Portfolio Risk Variance Calculation
- **Approach:** Given transaction asset weights $w$, calculate total portfolio variance $w^T \Sigma w$.
- **Syntax:** `w.T @ cov_mat @ w`

In [9]:
port_var = w.T @ cov_mat @ w
print('Total Portfolio Variance:', round(port_var, 6))

Total Portfolio Variance: 16.347974
